### ISSUE TITLE
i get this error while uploading doc 

### ISSUE THREAD

**Issue by AiJets** [SamurAIGPT/EmbedAI#57]
![image](https://github.com/SamurAIGPT/privateGPT/assets/135297142/d40273ce-a0d1-4839-9ed9-b948739a341c)

**Comment by Aashna2022** [comment]
i am also facing the same error.

**Comment by aice09** [comment]
Same error here.

**Comment by aice09** [comment]
@AiJets You need to make sure that you run **python privateGPT.py** along with **npm run dev**

![image](https://github.com/SamurAIGPT/privateGPT/assets/16074031/07cc70bd-7e5b-4d7f-a247-9198cae0c0b5)

**Comment by 11JR17** [comment]
> @AiJets You need to make sure that you run **python privateGPT.py** along with **npm run dev**
> 
> ![image](https://user-images.githubusercontent.com/16074031/246829033-07cc70bd-7e5b-4d7f-a247-9198cae0c0b5.png)

How long did it take for **npm rn dev** to finish processing? I've been here for a while
